version: '3.8'

services:
  app:
    image: laravelsail/php83-composer
    container_name: calendox_app
    working_dir: /var/www/html/laravel
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    command: sh -c "composer install && php artisan serve --host=0.0.0.0"

  mysql:
    image: mysql:8
    container_name: calendox_db
    restart: always
    environment:
      MYSQL_DATABASE: calendox
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: calendox_adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8081:8080"

volumes:
  dbdata:
